version: "3.8"
services:
  employee-app:
    image: "employee-app-image:latest"
    container_name: employee-app
    build: .
    restart: always
    ports:
      - 8085:8085
    environment:
      WAIT_HOSTS: mysql:3306  
    depends_on:
      - employee-mysql
      - employee-activemq
      
  employee-mysql:
    container_name: employee-mysql
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employeedb
      MYSQL_USER: mjc_user
      MYSQL_PASSWORD: mjcuser12345
      MYSQL_ROOT_PASSWORD: root
      
  employee-activemq:
    container_name: employee-activemq
    image: "rmohr/activemq:latest"
    restart: always
    ports:
      - 8161:8161
      - 61616:61616